In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import pickle

In [4]:
import pickle as pk

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
cars_Data = pd.read_csv('Cardetails.csv')

In [8]:
cars_Data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [9]:
cars_Data.shape

(8128, 13)

In [10]:
cars_Data.drop(columns = ['torque'], inplace = True)

In [11]:
cars_Data.shape

(8128, 12)

In [12]:
cars_Data.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
seats            221
dtype: int64

In [13]:
cars_Data.dropna(inplace=True)

In [14]:
cars_Data.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
seats            0
dtype: int64

In [15]:
cars_Data.shape

(7907, 12)

In [16]:
cars_Data.duplicated().sum()

1189

In [17]:
cars_Data.drop_duplicates(inplace = True)

In [18]:
cars_Data.shape

(6718, 12)

In [19]:
cars_Data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           6718 non-null   object 
 1   year           6718 non-null   int64  
 2   selling_price  6718 non-null   int64  
 3   km_driven      6718 non-null   int64  
 4   fuel           6718 non-null   object 
 5   seller_type    6718 non-null   object 
 6   transmission   6718 non-null   object 
 7   owner          6718 non-null   object 
 8   mileage        6718 non-null   object 
 9   engine         6718 non-null   object 
 10  max_power      6718 non-null   object 
 11  seats          6718 non-null   float64
dtypes: float64(1), int64(3), object(8)
memory usage: 682.3+ KB


In [20]:
for col in cars_Data.columns:
    print('Unique values of ' + col)
    print(cars_Data[col].unique())
    print("================================================")

Unique values of name
['Maruti Swift Dzire VDI' 'Skoda Rapid 1.5 TDI Ambition'
 'Honda City 2017-2020 EXi' ... 'Tata Nexon 1.5 Revotorq XT'
 'Ford Freestyle Titanium Plus Diesel BSIV'
 'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV']
Unique values of year
[2014 2006 2010 2007 2017 2001 2011 2013 2005 2009 2016 2012 2002 2015
 2018 2019 2008 2020 1999 2000 2003 2004 1994 1998 1997 1995 1996]
Unique values of selling_price
[  450000   370000   158000   225000   130000   440000    96000    45000
   350000   200000   500000    92000   280000   180000   400000   778000
   150000   680000   174000   950000   525000   600000   575000   275000
   300000   220000   254999   670000   730000   650000   330000   366000
  1149000   425000  2100000   925000   675000   819999   390000  1500000
   700000  1450000  1090000   850000  1650000  1750000  1590000  1689999
  1425000   265000   190000   630000   540000   448000   745000  1025000
   235000  1700000  1200000   610000  2500000   484999   315000  

In [21]:
def get_brand_name(car_name):
    car_name = car_name.split(' ')[0]
    return car_name.strip()

In [22]:
get_brand_name('Tata Nexon 1.5 Revotorq XT')

'Tata'

In [23]:
def clean_data(value):
    value=value.split(' ')[0]
    value = value.strip()
    if value == '':
        value = 0
    return float(value)

In [24]:
cars_Data['name'] = cars_Data['name'].apply(get_brand_name)

In [25]:
cars_Data['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'], dtype=object)

In [26]:
cars_Data['mileage'] = cars_Data['mileage'].apply(clean_data)

In [27]:
cars_Data['mileage'].unique()

array([23.4 , 21.14, 17.7 , 23.  , 16.1 , 20.14, 17.3 , 23.59, 20.  ,
       19.01, 19.3 , 18.9 , 18.15, 24.52, 19.7 , 22.54, 21.  , 25.5 ,
       26.59, 21.5 , 20.3 , 21.4 , 24.7 , 18.2 , 16.8 , 24.3 , 14.  ,
       18.6 , 33.44, 23.95, 17.  , 20.63, 13.93, 16.  , 17.8 , 18.5 ,
       12.55, 12.99, 14.8 , 13.5 , 26.  , 20.65, 27.3 , 11.36, 17.68,
       14.28, 18.53, 14.84, 21.12, 20.36, 21.27, 18.16, 22.  , 25.1 ,
       20.51, 21.66, 25.2 , 22.9 , 16.02, 20.54, 22.77, 15.71, 23.1 ,
       19.02, 19.81, 26.2 , 16.47, 15.04, 19.1 , 21.79, 18.8 , 21.21,
       15.37, 11.79, 19.  , 14.3 , 15.8 , 15.1 , 19.09, 22.32, 21.9 ,
       14.53, 21.63, 20.85, 20.45, 19.67, 23.01, 20.77, 17.92, 17.01,
       22.37, 19.33,  9.5 , 12.83, 22.48, 16.78, 14.67, 15.  , 13.96,
       18.  , 12.07, 26.21, 10.8 , 16.3 , 13.6 , 14.74, 15.6 , 19.56,
       22.69, 19.16, 18.12, 12.1 , 17.5 , 42.  , 20.4 , 21.1 , 19.44,
       13.  , 21.43, 22.95, 16.2 , 15.3 , 28.09, 17.4 , 19.4 , 26.6 ,
       17.6 , 28.4 ,

In [28]:
cars_Data['max_power'] = cars_Data['max_power'].apply(clean_data)
cars_Data['engine'] = cars_Data['engine'].apply(clean_data)

In [29]:
cars_Data['max_power'].unique()

array([ 74.   , 103.52 ,  78.   ,  90.   ,  88.2  ,  81.86 ,  57.5  ,
        37.   ,  67.1  ,  68.1  , 108.45 ,  60.   ,  73.9  ,  67.   ,
        82.   ,  88.5  ,  46.3  ,  88.73 ,  64.1  ,  98.6  ,  88.8  ,
        83.81 ,  83.1  ,  47.3  ,  73.8  ,  34.2  ,  35.   ,  81.83 ,
        40.3  , 121.3  , 138.03 , 160.77 , 117.3  , 116.3  ,  83.14 ,
        67.05 , 168.5  , 100.   , 120.7  ,  98.63 , 175.56 , 103.25 ,
       171.5  , 100.6  , 174.33 , 187.74 , 170.   ,  78.9  ,  88.76 ,
        86.8  , 108.495, 108.62 ,  93.7  , 103.6  ,  98.59 , 189.   ,
        67.04 ,  68.05 ,  58.2  ,  82.85 ,  81.8  ,  73.   , 120.   ,
        94.68 , 160.   ,  65.   , 155.   ,  69.01 , 126.32 , 138.1  ,
        83.8  , 126.2  ,  98.96 ,  62.1  ,  86.7  , 188.   , 214.56 ,
       177.   , 280.   , 148.31 , 254.79 , 190.   , 177.46 , 204.   ,
       141.   , 117.6  , 241.4  , 282.   , 150.   , 147.5  , 108.5  ,
       103.5  , 183.   , 181.04 , 157.7  , 164.7  ,  91.1  , 400.   ,
        68.   ,  75.

In [30]:
cars_Data['engine'].unique()

array([1248., 1498., 1497., 1396., 1298., 1197., 1061.,  796., 1364.,
       1399., 1461.,  993., 1198., 1199.,  998., 1591., 2179., 1368.,
       2982., 2494., 2143., 2477., 1462., 2755., 1968., 1798., 1196.,
       1373., 1598., 1998., 1086., 1194., 1172., 1405., 1582.,  999.,
       2487., 1999., 3604., 2987., 1995., 1451., 1969., 2967., 2497.,
       1797., 1991., 2362., 1493., 1599., 1341., 1794.,  799., 1193.,
       2696., 1495., 1186., 1047., 2498., 2956., 2523., 1120.,  624.,
       1496., 1984., 2354.,  814.,  793., 1799.,  936., 1956., 1997.,
       1499., 1948., 2997., 2489., 2499., 2609., 2953., 1150., 1994.,
       1388., 1527., 2199.,  995., 2993., 1586., 1390.,  909., 2393.,
       3198., 1339., 2835., 2092., 1595., 2496., 1596., 1597., 2596.,
       2148., 1299., 1590., 2231., 2694., 2200., 1795., 1896., 1796.,
       1422., 1489., 2359., 2197., 2999., 1781., 2650., 1343., 2446.,
       3498., 2198., 2776., 1950.])

In [31]:
for col in cars_Data.columns:
    print('Unique Vaues of ' + col)
    print(cars_Data[col].unique())
    print('<======================================================>')


Unique Vaues of name
['Maruti' 'Skoda' 'Honda' 'Hyundai' 'Toyota' 'Ford' 'Renault' 'Mahindra'
 'Tata' 'Chevrolet' 'Datsun' 'Jeep' 'Mercedes-Benz' 'Mitsubishi' 'Audi'
 'Volkswagen' 'BMW' 'Nissan' 'Lexus' 'Jaguar' 'Land' 'MG' 'Volvo' 'Daewoo'
 'Kia' 'Fiat' 'Force' 'Ambassador' 'Ashok' 'Isuzu' 'Opel']
<======================================================>
Unique Vaues of year
[2014 2006 2010 2007 2017 2001 2011 2013 2005 2009 2016 2012 2002 2015
 2018 2019 2008 2020 1999 2000 2003 2004 1994 1998 1997 1995 1996]
<======================================================>
Unique Vaues of selling_price
[  450000   370000   158000   225000   130000   440000    96000    45000
   350000   200000   500000    92000   280000   180000   400000   778000
   150000   680000   174000   950000   525000   600000   575000   275000
   300000   220000   254999   670000   730000   650000   330000   366000
  1149000   425000  2100000   925000   675000   819999   390000  1500000
   700000  1450000  1090000   85

In [33]:
cars_Data['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'],
                          [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31], inplace = True)

In [34]:
cars_Data['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [37]:
cars_Data['transmission'].replace(['Manual', 'Automatic'],
                                  [1,2], inplace= True)

In [38]:
cars_Data['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [40]:
cars_Data['fuel'].replace(['Diesel', 'Petrol', 'LPG', 'CNG'],
                          [1,2,3,4], inplace = True)

In [41]:
cars_Data['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [44]:
cars_Data['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'],
                                 [1,2,3], inplace = True)

In [45]:
cars_Data['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [47]:
cars_Data['owner'].replace(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'],
                           [1,2,3,4,5], inplace = True)

In [48]:
cars_Data

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0        1  2014         450000     145500     1            1             1   
1        2  2014         370000     120000     1            1             1   
2        3  2006         158000     140000     2            1             1   
3        4  2010         225000     127000     1            1             1   
4        1  2007         130000     120000     2            1             1   
...    ...   ...            ...        ...   ...          ...           ...   
8121     1  2013         260000      50000     2            1             1   
8122     4  2014         475000      80000     1            1             1   
8123     4  2013         320000     110000     2            1             1   
8124     4  2007         135000     119000     1            1             1   
8125     1  2009         382000     120000     1            1             1   

      owner  mileage  engine  max_power  seats  
0         1    23.40  1248.0      74.00    5.0  
1         2    21.14  1498.0     103.52    5.0  
2         3    17.70  1497.0      78.00    5.0  
3         1    23.00  1396.0      90.00    5.0  
4         1    16.10  1298.0      88.20    5.0  
...     ...      ...     ...        ...    ...  
8121      2    18.90   998.0      67.10    5.0  
8122      2    22.54  1396.0      88.73    5.0  
8123      1    18.50  1197.0      82.85    5.0  
8124      4    16.80  1493.0     110.00    5.0  
8125      1    19.30  1248.0      73.90    5.0  

[6718 rows x 12 columns]

In [49]:
cars_Data.reset_index(inplace = True)

In [50]:
cars_Data

index  name  year  selling_price  km_driven  fuel  seller_type  \
0         0     1  2014         450000     145500     1            1   
1         1     2  2014         370000     120000     1            1   
2         2     3  2006         158000     140000     2            1   
3         3     4  2010         225000     127000     1            1   
4         4     1  2007         130000     120000     2            1   
...     ...   ...   ...            ...        ...   ...          ...   
6713   8121     1  2013         260000      50000     2            1   
6714   8122     4  2014         475000      80000     1            1   
6715   8123     4  2013         320000     110000     2            1   
6716   8124     4  2007         135000     119000     1            1   
6717   8125     1  2009         382000     120000     1            1   

      transmission  owner  mileage  engine  max_power  seats  
0                1      1    23.40  1248.0      74.00    5.0  
1                1      2    21.14  1498.0     103.52    5.0  
2                1      3    17.70  1497.0      78.00    5.0  
3                1      1    23.00  1396.0      90.00    5.0  
4                1      1    16.10  1298.0      88.20    5.0  
...            ...    ...      ...     ...        ...    ...  
6713             1      2    18.90   998.0      67.10    5.0  
6714             1      2    22.54  1396.0      88.73    5.0  
6715             1      1    18.50  1197.0      82.85    5.0  
6716             1      4    16.80  1493.0     110.00    5.0  
6717             1      1    19.30  1248.0      73.90    5.0  

[6718 rows x 13 columns]

In [51]:
cars_Data.drop(columns = ['index'])

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0        1  2014         450000     145500     1            1             1   
1        2  2014         370000     120000     1            1             1   
2        3  2006         158000     140000     2            1             1   
3        4  2010         225000     127000     1            1             1   
4        1  2007         130000     120000     2            1             1   
...    ...   ...            ...        ...   ...          ...           ...   
6713     1  2013         260000      50000     2            1             1   
6714     4  2014         475000      80000     1            1             1   
6715     4  2013         320000     110000     2            1             1   
6716     4  2007         135000     119000     1            1             1   
6717     1  2009         382000     120000     1            1             1   

      owner  mileage  engine  max_power  seats  
0         1    23.40  1248.0      74.00    5.0  
1         2    21.14  1498.0     103.52    5.0  
2         3    17.70  1497.0      78.00    5.0  
3         1    23.00  1396.0      90.00    5.0  
4         1    16.10  1298.0      88.20    5.0  
...     ...      ...     ...        ...    ...  
6713      2    18.90   998.0      67.10    5.0  
6714      2    22.54  1396.0      88.73    5.0  
6715      1    18.50  1197.0      82.85    5.0  
6716      4    16.80  1493.0     110.00    5.0  
6717      1    19.30  1248.0      73.90    5.0  

[6718 rows x 12 columns]

In [52]:
input_data = cars_Data.drop(columns = ['selling_price'])

In [53]:
output_data = cars_Data['selling_price']

In [54]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size = 0.2)

In [55]:
model = LinearRegression()

model.fit(x_train, y_train)

In [56]:
model.fit(x_train, y_train)

LinearRegression()

In [57]:
predict = model.predict(x_test)

In [58]:
x_train.head(1)

index  name  year  km_driven  fuel  seller_type  transmission  owner  \
1238   1413     1  2015      30000     2            1             1      1   

      mileage  engine  max_power  seats  
1238    20.51   998.0      67.04    5.0

In [59]:
input_data_model = pd.DataFrame(
    [[5827, 1, 2026, 91000, 2, 1, 1, 2, 17.0, 1497.0, 118.0, 5.0]],
    columns = ['index' , 'name' , 'year' , 'km_driven' , 'fuel' , 'seller_type' , 'transmission' , 'owner' , 'mileage' , 'engine' , 'max_power' , 'seats'])


In [60]:
input_data_model

index  name  year  km_driven  fuel  seller_type  transmission  owner  \
0   5827     1  2026      91000     2            1             1      2   

   mileage  engine  max_power  seats  
0     17.0  1497.0      118.0    5.0

In [61]:
model.predict(input_data_model)

array([1108830.02102713])

In [63]:
import pickle as pk

In [64]:
pk.dump(model,open('model.pkl','wb'))